"""
Checks whether the current Dhan credentials (DHAN_CLIENT_ID + DHAN_ACCESS_TOKEN,
i.e. "Option B" static-token auth) are still valid, and sends a Telegram
alert if not - so you find out *before* market open that you need to
refresh the token, rather than the scanner silently falling back to
yfinance for the whole day without you noticing.

Static Dhan access tokens expire every 24h and must be regenerated by hand
from web.dhan.co (My Profile -> Access DhanHQ APIs -> Generate Access
Token) and pasted into the DHAN_ACCESS_TOKEN GitHub secret. This script
doesn't (and can't) refresh it for you - it just checks and reminds.

Exit code is always 0 (non-blocking) - this should never fail a workflow
run, it's purely informational.
"""
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))

from smc_scanner.config import Config
from smc_scanner.data_sources.dhan import DhanDataSource, DhanAuthError
from smc_scanner.notify import send_telegram

# A cheap, well-known, always-listed symbol to test with (Reliance Industries)
TEST_SECURITY_ID = "2885"


def check_token() -> tuple[bool, str]:
    """Returns (is_valid, message)."""
    if not os.environ.get("DHAN_CLIENT_ID"):
        return False, "DHAN_CLIENT_ID is not set at all - Dhan is not configured."

    if os.environ.get("DHAN_TOTP_SECRET"):
        return True, "Using TOTP auto-auth (Option A) - token refreshes itself, nothing to check."

    if not os.environ.get("DHAN_ACCESS_TOKEN"):
        return False, "DHAN_ACCESS_TOKEN is not set - Dhan is not configured (Option B needs this)."

    try:
        cfg = Config()
        ds = DhanDataSource(cfg)
        from datetime import datetime, timedelta
        to_date = datetime.now().strftime("%Y-%m-%d")
        from_date = (datetime.now() - timedelta(days=5)).strftime("%Y-%m-%d")
        df = ds.fetch_daily(TEST_SECURITY_ID, "NSE_EQ", "EQUITY", from_date, to_date)
        if df is None or df.empty:
            return False, "Dhan returned no data for a known test symbol - token may be invalid/expired."
        return True, "Dhan access token is valid."
    except DhanAuthError as e:
        return False, f"Dhan auth error: {e}"
    except Exception as e:
        msg = str(e)
        if "401" in msg or "DH-901" in msg or "expired" in msg.lower() or "invalid" in msg.lower():
            return False, f"Dhan access token looks expired/invalid: {msg[:200]}"
        # some other transient error (network, rate limit) - don't cry wolf
        return True, f"Dhan check inconclusive (treating as OK, not an auth issue): {msg[:200]}"


if __name__ == "__main__":
    valid, message = check_token()
    print(f"[dhan-token-check] valid={valid} :: {message}")

    if not valid:
        alert = (
            "🔑 *Dhan token needs attention*\n"
            f"{message}\n\n"
            "Refresh it: web.dhan.co -> My Profile -> Access DhanHQ APIs -> "
            "Generate Access Token, then update the `DHAN_ACCESS_TOKEN` "
            "GitHub secret before market open.\n\n"
            "_(The scanner will keep running on the yfinance fallback in the "
            "meantime, but Dhan gives more accurate/real-time data.)_"
        )
        send_telegram(alert)

    sys.exit(0)
